#ifndef UAVPC_UTILS_COMPATIBILITY_MACROS_HPP_
#define UAVPC_UTILS_COMPATIBILITY_MACROS_HPP_

#if _WIN32 || _WIN64
#define UAVPC_SOCKET_TYPE    SOCKET
#define UAVPC_SOCKET_DEFAULT INVALID_SOCKET
#else
#define UAVPC_SOCKET_TYPE    int
#define UAVPC_SOCKET_DEFAULT -1
#endif

#endif
